module Credential
  CONSUMER_KEY = 'YOUR_CONSUMER_KEY_HERE'
  CONSUMER_SECRET = 'YOUR_CONSUMER_SECRET_HERE'
  ACCESS_TOKEN = 'YOUR_ACCESS_TOKEN_HERE'
  ACCESS_TOKEN_SECRET = 'YOUR_ACCESS_TOKEN_SECRET_HERE'
end
